version: "3.1"
services:

  mysql:
    image: mariadb:latest
    container_name: mysql
    working_dir: /application
    env_file:
      - server/.env
    volumes:
      - .:/application
      - ./storage-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "8083:3306"

  webserver:
    image: nginx:alpine
    container_name: webserver
    working_dir: /application
    env_file:
      - server/.env
    volumes:
      - ./server:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"

  php-fpm:
    build: docker/php-fpm
    container_name: php-fpm
    working_dir: /application
    env_file:
      - server/.env
    volumes:
      - ./server:/application

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file:
      - server/.env
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - '8082:80'
    links:
      - mysql
    env_file:
      - server/.env
    environment:
      - PMA_HOST=${DB_HOST}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}